import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { resorts, NewResort } from "../src/db/schema";
import "dotenv/config";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is not set");
}

const sql = neon(process.env.DATABASE_URL);
const db = drizzle(sql);

// Helper to create slug from name
function createSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim();
}

// US Regions
type Region = "West" | "Rockies" | "Midwest" | "Northeast" | "Southeast";

// State to region mapping
const stateRegions: Record<string, Region> = {
  // West
  CA: "West",
  OR: "West",
  WA: "West",
  AK: "West",
  HI: "West",
  NV: "West",
  // Rockies
  CO: "Rockies",
  UT: "Rockies",
  WY: "Rockies",
  MT: "Rockies",
  ID: "Rockies",
  NM: "Rockies",
  AZ: "Rockies",
  // Midwest
  MI: "Midwest",
  WI: "Midwest",
  MN: "Midwest",
  IA: "Midwest",
  IL: "Midwest",
  IN: "Midwest",
  OH: "Midwest",
  ND: "Midwest",
  SD: "Midwest",
  NE: "Midwest",
  KS: "Midwest",
  MO: "Midwest",
  // Northeast
  ME: "Northeast",
  NH: "Northeast",
  VT: "Northeast",
  MA: "Northeast",
  CT: "Northeast",
  RI: "Northeast",
  NY: "Northeast",
  NJ: "Northeast",
  PA: "Northeast",
  // Southeast
  WV: "Southeast",
  VA: "Southeast",
  MD: "Southeast",
  NC: "Southeast",
  TN: "Southeast",
  GA: "Southeast",
  AL: "Southeast",
  SC: "Southeast",
  KY: "Southeast",
};

// State to timezone mapping
const stateTimezones: Record<string, string> = {
  // Pacific
  CA: "America/Los_Angeles",
  OR: "America/Los_Angeles",
  WA: "America/Los_Angeles",
  NV: "America/Los_Angeles",
  // Alaska
  AK: "America/Anchorage",
  // Mountain
  CO: "America/Denver",
  UT: "America/Denver",
  WY: "America/Denver",
  MT: "America/Denver",
  ID: "America/Boise",
  NM: "America/Denver",
  AZ: "America/Phoenix",
  // Central
  MN: "America/Chicago",
  WI: "America/Chicago",
  IA: "America/Chicago",
  IL: "America/Chicago",
  IN: "America/Indiana/Indianapolis",
  MO: "America/Chicago",
  ND: "America/Chicago",
  SD: "America/Chicago",
  NE: "America/Chicago",
  KS: "America/Chicago",
  // Eastern
  MI: "America/Detroit",
  OH: "America/New_York",
  NY: "America/New_York",
  PA: "America/New_York",
  NJ: "America/New_York",
  CT: "America/New_York",
  RI: "America/New_York",
  MA: "America/New_York",
  VT: "America/New_York",
  NH: "America/New_York",
  ME: "America/New_York",
  WV: "America/New_York",
  VA: "America/New_York",
  MD: "America/New_York",
  NC: "America/New_York",
  TN: "America/New_York",
  GA: "America/New_York",
  AL: "America/Chicago",
  SC: "America/New_York",
  KY: "America/New_York",
};

interface ResortData {
  name: string;
  state: string;
  lat: number;
  lon: number;
  websiteUrl?: string;
  skiresortinfoId?: string;
}

// Comprehensive US Ski Resort Data
const resortData: ResortData[] = [
  // ============================================================
  // COLORADO (Rockies) - 32 resorts
  // ============================================================
  {
    name: "Vail",
    state: "CO",
    lat: 39.6403,
    lon: -106.3742,
    websiteUrl: "https://www.vail.com",
    skiresortinfoId: "vail",
  },
  {
    name: "Breckenridge",
    state: "CO",
    lat: 39.4817,
    lon: -106.0384,
    websiteUrl: "https://www.breckenridge.com",
    skiresortinfoId: "breckenridge",
  },
  {
    name: "Aspen Mountain",
    state: "CO",
    lat: 39.1875,
    lon: -106.8199,
    websiteUrl: "https://www.aspensnowmass.com",
    skiresortinfoId: "aspen-mountain",
  },
  {
    name: "Aspen Highlands",
    state: "CO",
    lat: 39.1792,
    lon: -106.8556,
    websiteUrl: "https://www.aspensnowmass.com",
    skiresortinfoId: "aspen-highlands",
  },
  {
    name: "Snowmass",
    state: "CO",
    lat: 39.213,
    lon: -106.9378,
    websiteUrl: "https://www.aspensnowmass.com",
    skiresortinfoId: "snowmass",
  },
  {
    name: "Buttermilk",
    state: "CO",
    lat: 39.2069,
    lon: -106.8686,
    websiteUrl: "https://www.aspensnowmass.com",
    skiresortinfoId: "buttermilk",
  },
  {
    name: "Beaver Creek",
    state: "CO",
    lat: 39.6042,
    lon: -106.5165,
    websiteUrl: "https://www.beavercreek.com",
    skiresortinfoId: "beaver-creek",
  },
  {
    name: "Keystone",
    state: "CO",
    lat: 39.6069,
    lon: -105.9508,
    websiteUrl: "https://www.keystoneresort.com",
    skiresortinfoId: "keystone",
  },
  {
    name: "Copper Mountain",
    state: "CO",
    lat: 39.5022,
    lon: -106.1497,
    websiteUrl: "https://www.coppercolorado.com",
    skiresortinfoId: "copper-mountain",
  },
  {
    name: "Winter Park",
    state: "CO",
    lat: 39.8841,
    lon: -105.7625,
    websiteUrl: "https://www.winterparkresort.com",
    skiresortinfoId: "winter-park",
  },
  {
    name: "Steamboat",
    state: "CO",
    lat: 40.4572,
    lon: -106.8045,
    websiteUrl: "https://www.steamboat.com",
    skiresortinfoId: "steamboat",
  },
  {
    name: "Telluride",
    state: "CO",
    lat: 37.9375,
    lon: -107.8123,
    websiteUrl: "https://www.tellurideskiresort.com",
    skiresortinfoId: "telluride",
  },
  {
    name: "Crested Butte",
    state: "CO",
    lat: 38.8994,
    lon: -106.9653,
    websiteUrl: "https://www.skicb.com",
    skiresortinfoId: "crested-butte",
  },
  {
    name: "Arapahoe Basin",
    state: "CO",
    lat: 39.6425,
    lon: -105.8719,
    websiteUrl: "https://www.arapahoebasin.com",
    skiresortinfoId: "arapahoe-basin",
  },
  {
    name: "Loveland",
    state: "CO",
    lat: 39.68,
    lon: -105.8978,
    websiteUrl: "https://skiloveland.com",
    skiresortinfoId: "loveland",
  },
  {
    name: "Eldora Mountain",
    state: "CO",
    lat: 39.9372,
    lon: -105.5828,
    websiteUrl: "https://www.eldora.com",
    skiresortinfoId: "eldora",
  },
  {
    name: "Monarch Mountain",
    state: "CO",
    lat: 38.5125,
    lon: -106.3322,
    websiteUrl: "https://skimonarch.com",
    skiresortinfoId: "monarch-mountain",
  },
  {
    name: "Purgatory",
    state: "CO",
    lat: 37.6303,
    lon: -107.8142,
    websiteUrl: "https://www.purgatoryresort.com",
    skiresortinfoId: "purgatory",
  },
  {
    name: "Wolf Creek",
    state: "CO",
    lat: 37.4697,
    lon: -106.7931,
    websiteUrl: "https://wolfcreekski.com",
    skiresortinfoId: "wolf-creek",
  },
  {
    name: "Silverton Mountain",
    state: "CO",
    lat: 37.8847,
    lon: -107.6653,
    websiteUrl: "https://silvertonmountain.com",
    skiresortinfoId: "silverton-mountain",
  },
  {
    name: "Ski Cooper",
    state: "CO",
    lat: 39.3617,
    lon: -106.2992,
    websiteUrl: "https://skicooper.com",
    skiresortinfoId: "ski-cooper",
  },
  {
    name: "Sunlight Mountain",
    state: "CO",
    lat: 39.4003,
    lon: -107.3392,
    websiteUrl: "https://sunlightmtn.com",
    skiresortinfoId: "sunlight-mountain",
  },
  {
    name: "Powderhorn",
    state: "CO",
    lat: 39.0686,
    lon: -108.1508,
    websiteUrl: "https://powderhorn.com",
    skiresortinfoId: "powderhorn",
  },
  {
    name: "Howelsen Hill",
    state: "CO",
    lat: 40.4847,
    lon: -106.8331,
    websiteUrl: "https://steamboatsprings.net/150/Howelsen-Hill-Ski-Area",
    skiresortinfoId: "howelsen-hill",
  },
  {
    name: "Echo Mountain",
    state: "CO",
    lat: 39.6858,
    lon: -105.5178,
    websiteUrl: "https://echomntn.com",
    skiresortinfoId: "echo-mountain",
  },
  {
    name: "Granby Ranch",
    state: "CO",
    lat: 40.0464,
    lon: -105.9117,
    websiteUrl: "https://granbyranch.com",
    skiresortinfoId: "granby-ranch",
  },
  {
    name: "Kendall Mountain",
    state: "CO",
    lat: 37.8117,
    lon: -107.6656,
    websiteUrl: "https://www.townofsilverton.net/recreation",
    skiresortinfoId: "kendall-mountain",
  },
  {
    name: "Hesperus",
    state: "CO",
    lat: 37.2917,
    lon: -108.0531,
    websiteUrl: "https://ski-hesperus.com",
    skiresortinfoId: "hesperus",
  },
  {
    name: "Chapman Hill",
    state: "CO",
    lat: 37.2739,
    lon: -107.8742,
    websiteUrl: "https://www.durangogov.org/Facilities/Facility/Details/Chapman-Hill-Ski-Area-30",
    skiresortinfoId: "chapman-hill",
  },
  {
    name: "Cuchara Mountain Park",
    state: "CO",
    lat: 37.2936,
    lon: -105.1019,
    websiteUrl: "https://cucharamountain.com",
    skiresortinfoId: "cuchara-mountain",
  },
  {
    name: "Ski Granby Ranch",
    state: "CO",
    lat: 40.0464,
    lon: -105.9117,
    websiteUrl: "https://granbyranch.com",
    skiresortinfoId: "ski-granby-ranch",
  },
  {
    name: "Bluebird Backcountry",
    state: "CO",
    lat: 40.0667,
    lon: -106.0833,
    websiteUrl: "https://bluebirdbackcountry.com",
    skiresortinfoId: "bluebird-backcountry",
  },

  // ============================================================
  // UTAH (Rockies) - 15 resorts
  // ============================================================
  {
    name: "Park City Mountain",
    state: "UT",
    lat: 40.6514,
    lon: -111.508,
    websiteUrl: "https://www.parkcitymountain.com",
    skiresortinfoId: "park-city",
  },
  {
    name: "Deer Valley",
    state: "UT",
    lat: 40.6375,
    lon: -111.4783,
    websiteUrl: "https://www.deervalley.com",
    skiresortinfoId: "deer-valley",
  },
  {
    name: "Snowbird",
    state: "UT",
    lat: 40.583,
    lon: -111.6538,
    websiteUrl: "https://www.snowbird.com",
    skiresortinfoId: "snowbird",
  },
  {
    name: "Alta",
    state: "UT",
    lat: 40.5884,
    lon: -111.6386,
    websiteUrl: "https://www.alta.com",
    skiresortinfoId: "alta",
  },
  {
    name: "Brighton",
    state: "UT",
    lat: 40.598,
    lon: -111.5833,
    websiteUrl: "https://www.brightonresort.com",
    skiresortinfoId: "brighton",
  },
  {
    name: "Solitude",
    state: "UT",
    lat: 40.6197,
    lon: -111.5922,
    websiteUrl: "https://www.solitudemountain.com",
    skiresortinfoId: "solitude",
  },
  {
    name: "Snowbasin",
    state: "UT",
    lat: 41.2161,
    lon: -111.8569,
    websiteUrl: "https://www.snowbasin.com",
    skiresortinfoId: "snowbasin",
  },
  {
    name: "Powder Mountain",
    state: "UT",
    lat: 41.3797,
    lon: -111.7806,
    websiteUrl: "https://www.powdermountain.com",
    skiresortinfoId: "powder-mountain",
  },
  {
    name: "Sundance",
    state: "UT",
    lat: 40.3903,
    lon: -111.5889,
    websiteUrl: "https://www.sundanceresort.com",
    skiresortinfoId: "sundance",
  },
  {
    name: "Brian Head",
    state: "UT",
    lat: 37.7022,
    lon: -112.8497,
    websiteUrl: "https://www.brianhead.com",
    skiresortinfoId: "brian-head",
  },
  {
    name: "Eagle Point",
    state: "UT",
    lat: 38.3203,
    lon: -112.3836,
    websiteUrl: "https://www.eaglepointresort.com",
    skiresortinfoId: "eagle-point",
  },
  {
    name: "Beaver Mountain",
    state: "UT",
    lat: 41.9681,
    lon: -111.5403,
    websiteUrl: "https://www.skithebeav.com",
    skiresortinfoId: "beaver-mountain",
  },
  {
    name: "Cherry Peak",
    state: "UT",
    lat: 41.9297,
    lon: -111.7486,
    websiteUrl: "https://www.skicherrypeak.com",
    skiresortinfoId: "cherry-peak",
  },
  {
    name: "Nordic Valley",
    state: "UT",
    lat: 41.31,
    lon: -111.8647,
    websiteUrl: "https://www.nordicvalley.com",
    skiresortinfoId: "nordic-valley",
  },
  {
    name: "Woodward Park City",
    state: "UT",
    lat: 40.7178,
    lon: -111.5358,
    websiteUrl: "https://www.woodwardparkcity.com",
    skiresortinfoId: "woodward-park-city",
  },

  // ============================================================
  // CALIFORNIA (West) - 33 resorts
  // ============================================================
  {
    name: "Mammoth Mountain",
    state: "CA",
    lat: 37.6308,
    lon: -119.0326,
    websiteUrl: "https://www.mammothmountain.com",
    skiresortinfoId: "mammoth-mountain",
  },
  {
    name: "Palisades Tahoe",
    state: "CA",
    lat: 39.1969,
    lon: -120.2358,
    websiteUrl: "https://www.palisadestahoe.com",
    skiresortinfoId: "palisades-tahoe",
  },
  {
    name: "Heavenly",
    state: "CA",
    lat: 38.9353,
    lon: -119.94,
    websiteUrl: "https://www.skiheavenly.com",
    skiresortinfoId: "heavenly",
  },
  {
    name: "Kirkwood",
    state: "CA",
    lat: 38.685,
    lon: -120.0653,
    websiteUrl: "https://www.kirkwood.com",
    skiresortinfoId: "kirkwood",
  },
  {
    name: "Northstar California",
    state: "CA",
    lat: 39.2746,
    lon: -120.1211,
    websiteUrl: "https://www.northstarcalifornia.com",
    skiresortinfoId: "northstar-california",
  },
  {
    name: "Sugar Bowl",
    state: "CA",
    lat: 39.3047,
    lon: -120.3342,
    websiteUrl: "https://www.sugarbowl.com",
    skiresortinfoId: "sugar-bowl",
  },
  {
    name: "Sierra at Tahoe",
    state: "CA",
    lat: 38.7994,
    lon: -120.0803,
    websiteUrl: "https://www.sierraattahoe.com",
    skiresortinfoId: "sierra-at-tahoe",
  },
  {
    name: "Boreal Mountain",
    state: "CA",
    lat: 39.3328,
    lon: -120.3483,
    websiteUrl: "https://www.rideboreal.com",
    skiresortinfoId: "boreal-mountain",
  },
  {
    name: "Soda Springs",
    state: "CA",
    lat: 39.3192,
    lon: -120.3817,
    websiteUrl: "https://www.skisodasprings.com",
    skiresortinfoId: "soda-springs",
  },
  {
    name: "Tahoe Donner",
    state: "CA",
    lat: 39.3519,
    lon: -120.2869,
    websiteUrl: "https://www.tahoedonner.com/downhill-ski",
    skiresortinfoId: "tahoe-donner",
  },
  {
    name: "Diamond Peak",
    state: "CA",
    lat: 39.2536,
    lon: -119.9208,
    websiteUrl: "https://www.diamondpeak.com",
    skiresortinfoId: "diamond-peak",
  },
  {
    name: "Mt. Rose",
    state: "CA",
    lat: 39.3297,
    lon: -119.8853,
    websiteUrl: "https://skirose.com",
    skiresortinfoId: "mt-rose",
  },
  {
    name: "Homewood Mountain",
    state: "CA",
    lat: 39.0864,
    lon: -120.1656,
    websiteUrl: "https://www.skihomewood.com",
    skiresortinfoId: "homewood-mountain",
  },
  {
    name: "Bear Valley",
    state: "CA",
    lat: 38.4697,
    lon: -120.0422,
    websiteUrl: "https://www.bearvalley.com",
    skiresortinfoId: "bear-valley",
  },
  {
    name: "Dodge Ridge",
    state: "CA",
    lat: 38.1894,
    lon: -119.9567,
    websiteUrl: "https://www.dodgeridge.com",
    skiresortinfoId: "dodge-ridge",
  },
  {
    name: "China Peak",
    state: "CA",
    lat: 37.2336,
    lon: -119.1572,
    websiteUrl: "https://www.skichinapeak.com",
    skiresortinfoId: "china-peak",
  },
  {
    name: "Mountain High",
    state: "CA",
    lat: 34.3722,
    lon: -117.6911,
    websiteUrl: "https://www.mthigh.com",
    skiresortinfoId: "mountain-high",
  },
  {
    name: "Big Bear Mountain",
    state: "CA",
    lat: 34.2286,
    lon: -116.8908,
    websiteUrl: "https://www.bigbearmountainresort.com",
    skiresortinfoId: "big-bear-mountain",
  },
  {
    name: "Snow Summit",
    state: "CA",
    lat: 34.2361,
    lon: -116.865,
    websiteUrl: "https://www.bigbearmountainresort.com",
    skiresortinfoId: "snow-summit",
  },
  {
    name: "Snow Valley",
    state: "CA",
    lat: 34.2258,
    lon: -117.0375,
    websiteUrl: "https://www.snow-valley.com",
    skiresortinfoId: "snow-valley",
  },
  {
    name: "Mt. Baldy",
    state: "CA",
    lat: 34.2453,
    lon: -117.6531,
    websiteUrl: "https://www.mtbaldyresort.com",
    skiresortinfoId: "mt-baldy",
  },
  {
    name: "June Mountain",
    state: "CA",
    lat: 37.7672,
    lon: -119.0894,
    websiteUrl: "https://www.junemountain.com",
    skiresortinfoId: "june-mountain",
  },
  {
    name: "Mt. Shasta Ski Park",
    state: "CA",
    lat: 41.3156,
    lon: -122.2025,
    websiteUrl: "https://www.skipark.com",
    skiresortinfoId: "mt-shasta-ski-park",
  },
  {
    name: "Badger Pass",
    state: "CA",
    lat: 37.6625,
    lon: -119.6636,
    websiteUrl: "https://www.travelyosemite.com/winter/badger-pass-ski-area",
    skiresortinfoId: "badger-pass",
  },
  {
    name: "Donner Ski Ranch",
    state: "CA",
    lat: 39.3183,
    lon: -120.33,
    websiteUrl: "https://www.donnerskiranch.com",
    skiresortinfoId: "donner-ski-ranch",
  },
  {
    name: "Granlibakken",
    state: "CA",
    lat: 39.1667,
    lon: -120.1369,
    websiteUrl: "https://www.granlibakken.com",
    skiresortinfoId: "granlibakken",
  },
  {
    name: "Alta Sierra",
    state: "CA",
    lat: 35.73,
    lon: -118.5425,
    websiteUrl: "https://www.altasierra.com",
    skiresortinfoId: "alta-sierra",
  },
  {
    name: "Yosemite Ski & Snowboard Area",
    state: "CA",
    lat: 37.6625,
    lon: -119.6636,
    websiteUrl: "https://www.travelyosemite.com",
    skiresortinfoId: "yosemite-ski",
  },
  {
    name: "Lassen Park Ski Area",
    state: "CA",
    lat: 40.4653,
    lon: -121.5269,
    websiteUrl: "https://www.nps.gov/lavo",
    skiresortinfoId: "lassen-park",
  },
  {
    name: "Buckhorn",
    state: "CA",
    lat: 34.3394,
    lon: -117.9094,
    websiteUrl: "https://www.buckhornlodge.com",
    skiresortinfoId: "buckhorn",
  },
  {
    name: "Lee Canyon",
    state: "NV",
    lat: 36.3019,
    lon: -115.6797,
    websiteUrl: "https://www.leecanyonlv.com",
    skiresortinfoId: "lee-canyon",
  },
  {
    name: "Sky Tavern",
    state: "NV",
    lat: 39.3117,
    lon: -119.8519,
    websiteUrl: "https://skytavern.org",
    skiresortinfoId: "sky-tavern",
  },
  {
    name: "Royal Gorge",
    state: "CA",
    lat: 39.35,
    lon: -120.3667,
    websiteUrl: "https://www.royalgorge.com",
    skiresortinfoId: "royal-gorge",
  },

  // ============================================================
  // VERMONT (Northeast) - 21 resorts
  // ============================================================
  {
    name: "Killington",
    state: "VT",
    lat: 43.6045,
    lon: -72.8201,
    websiteUrl: "https://www.killington.com",
    skiresortinfoId: "killington",
  },
  {
    name: "Stowe",
    state: "VT",
    lat: 44.5303,
    lon: -72.7814,
    websiteUrl: "https://www.stowe.com",
    skiresortinfoId: "stowe",
  },
  {
    name: "Sugarbush",
    state: "VT",
    lat: 44.1358,
    lon: -72.9022,
    websiteUrl: "https://www.sugarbush.com",
    skiresortinfoId: "sugarbush",
  },
  {
    name: "Jay Peak",
    state: "VT",
    lat: 44.9275,
    lon: -72.5056,
    websiteUrl: "https://jaypeakresort.com",
    skiresortinfoId: "jay-peak",
  },
  {
    name: "Okemo",
    state: "VT",
    lat: 43.4017,
    lon: -72.7172,
    websiteUrl: "https://www.okemo.com",
    skiresortinfoId: "okemo",
  },
  {
    name: "Stratton",
    state: "VT",
    lat: 43.1136,
    lon: -72.9078,
    websiteUrl: "https://www.stratton.com",
    skiresortinfoId: "stratton",
  },
  {
    name: "Mount Snow",
    state: "VT",
    lat: 42.9603,
    lon: -72.9206,
    websiteUrl: "https://www.mountsnow.com",
    skiresortinfoId: "mount-snow",
  },
  {
    name: "Mad River Glen",
    state: "VT",
    lat: 44.2025,
    lon: -72.9169,
    websiteUrl: "https://www.madriverglen.com",
    skiresortinfoId: "mad-river-glen",
  },
  {
    name: "Bolton Valley",
    state: "VT",
    lat: 44.4208,
    lon: -72.85,
    websiteUrl: "https://www.boltonvalley.com",
    skiresortinfoId: "bolton-valley",
  },
  {
    name: "Smugglers Notch",
    state: "VT",
    lat: 44.5875,
    lon: -72.7872,
    websiteUrl: "https://www.smuggs.com",
    skiresortinfoId: "smugglers-notch",
  },
  {
    name: "Burke Mountain",
    state: "VT",
    lat: 44.5678,
    lon: -71.9017,
    websiteUrl: "https://www.skiburke.com",
    skiresortinfoId: "burke-mountain",
  },
  {
    name: "Bromley Mountain",
    state: "VT",
    lat: 43.2172,
    lon: -72.9344,
    websiteUrl: "https://www.bromley.com",
    skiresortinfoId: "bromley-mountain",
  },
  {
    name: "Magic Mountain",
    state: "VT",
    lat: 43.2042,
    lon: -72.7781,
    websiteUrl: "https://www.magicmtn.com",
    skiresortinfoId: "magic-mountain",
  },
  {
    name: "Pico Mountain",
    state: "VT",
    lat: 43.6611,
    lon: -72.8442,
    websiteUrl: "https://www.picomountain.com",
    skiresortinfoId: "pico-mountain",
  },
  {
    name: "Suicide Six",
    state: "VT",
    lat: 43.665,
    lon: -72.5147,
    websiteUrl: "https://www.woodstockinn.com/suicide-six-ski-area",
    skiresortinfoId: "suicide-six",
  },
  {
    name: "Middlebury College Snow Bowl",
    state: "VT",
    lat: 43.9461,
    lon: -72.9511,
    websiteUrl: "https://www.middlebury.edu/snowbowl",
    skiresortinfoId: "middlebury-snow-bowl",
  },
  {
    name: "Cochrans",
    state: "VT",
    lat: 44.3661,
    lon: -72.9189,
    websiteUrl: "https://cochranskiarea.com",
    skiresortinfoId: "cochrans",
  },
  {
    name: "Northeast Slopes",
    state: "VT",
    lat: 44.3842,
    lon: -72.37,
    websiteUrl: "https://www.northeastslopes.org",
    skiresortinfoId: "northeast-slopes",
  },
  {
    name: "Ascutney Outdoors",
    state: "VT",
    lat: 43.4344,
    lon: -72.4425,
    websiteUrl: "https://ascutneyoutdoors.org",
    skiresortinfoId: "ascutney-outdoors",
  },
  {
    name: "Saskadena Six",
    state: "VT",
    lat: 43.3883,
    lon: -72.4597,
    websiteUrl: "https://saskadenasix.com",
    skiresortinfoId: "saskadena-six",
  },
  {
    name: "Lyndon Outing Club",
    state: "VT",
    lat: 44.5169,
    lon: -72.0153,
    websiteUrl: "https://www.lyndonoutingclub.org",
    skiresortinfoId: "lyndon-outing-club",
  },

  // ============================================================
  // NEW HAMPSHIRE (Northeast) - 17 resorts
  // ============================================================
  {
    name: "Bretton Woods",
    state: "NH",
    lat: 44.2592,
    lon: -71.4408,
    websiteUrl: "https://www.brettonwoods.com",
    skiresortinfoId: "bretton-woods",
  },
  {
    name: "Cannon Mountain",
    state: "NH",
    lat: 44.1558,
    lon: -71.6983,
    websiteUrl: "https://www.cannonmt.com",
    skiresortinfoId: "cannon-mountain",
  },
  {
    name: "Loon Mountain",
    state: "NH",
    lat: 44.0369,
    lon: -71.6208,
    websiteUrl: "https://www.loonmtn.com",
    skiresortinfoId: "loon-mountain",
  },
  {
    name: "Waterville Valley",
    state: "NH",
    lat: 43.965,
    lon: -71.5286,
    websiteUrl: "https://www.waterville.com",
    skiresortinfoId: "waterville-valley",
  },
  {
    name: "Wildcat Mountain",
    state: "NH",
    lat: 44.2631,
    lon: -71.24,
    websiteUrl: "https://www.skiwildcat.com",
    skiresortinfoId: "wildcat-mountain",
  },
  {
    name: "Attitash",
    state: "NH",
    lat: 44.0833,
    lon: -71.2286,
    websiteUrl: "https://www.attitash.com",
    skiresortinfoId: "attitash",
  },
  {
    name: "Cranmore Mountain",
    state: "NH",
    lat: 44.0558,
    lon: -71.1108,
    websiteUrl: "https://www.cranmore.com",
    skiresortinfoId: "cranmore-mountain",
  },
  {
    name: "Mount Sunapee",
    state: "NH",
    lat: 43.3272,
    lon: -72.0839,
    websiteUrl: "https://www.mountsunapee.com",
    skiresortinfoId: "mount-sunapee",
  },
  {
    name: "Ragged Mountain",
    state: "NH",
    lat: 43.4903,
    lon: -71.8519,
    websiteUrl: "https://www.raggedmountainresort.com",
    skiresortinfoId: "ragged-mountain",
  },
  {
    name: "Gunstock",
    state: "NH",
    lat: 43.5467,
    lon: -71.3656,
    websiteUrl: "https://www.gunstock.com",
    skiresortinfoId: "gunstock",
  },
  {
    name: "Pats Peak",
    state: "NH",
    lat: 43.1372,
    lon: -71.8025,
    websiteUrl: "https://www.patspeak.com",
    skiresortinfoId: "pats-peak",
  },
  {
    name: "Black Mountain",
    state: "NH",
    lat: 44.1158,
    lon: -71.0897,
    websiteUrl: "https://www.blackmt.com",
    skiresortinfoId: "black-mountain-nh",
  },
  {
    name: "Crotched Mountain",
    state: "NH",
    lat: 42.9875,
    lon: -71.8772,
    websiteUrl: "https://www.crotchedmtn.com",
    skiresortinfoId: "crotched-mountain",
  },
  {
    name: "King Pine",
    state: "NH",
    lat: 43.8694,
    lon: -71.1569,
    websiteUrl: "https://www.kingpine.com",
    skiresortinfoId: "king-pine",
  },
  {
    name: "Dartmouth Skiway",
    state: "NH",
    lat: 43.7533,
    lon: -72.0989,
    websiteUrl: "https://skiway.dartmouth.edu",
    skiresortinfoId: "dartmouth-skiway",
  },
  {
    name: "Whaleback Mountain",
    state: "NH",
    lat: 43.7122,
    lon: -72.2028,
    websiteUrl: "https://www.whaleback.com",
    skiresortinfoId: "whaleback-mountain",
  },
  {
    name: "McIntyre Ski Area",
    state: "NH",
    lat: 43.0325,
    lon: -71.4489,
    websiteUrl: "https://www.mcintyreskiarea.com",
    skiresortinfoId: "mcintyre-ski-area",
  },

  // ============================================================
  // MAINE (Northeast) - 10 resorts
  // ============================================================
  {
    name: "Sugarloaf",
    state: "ME",
    lat: 45.0314,
    lon: -70.3131,
    websiteUrl: "https://www.sugarloaf.com",
    skiresortinfoId: "sugarloaf",
  },
  {
    name: "Sunday River",
    state: "ME",
    lat: 44.4736,
    lon: -70.8567,
    websiteUrl: "https://www.sundayriver.com",
    skiresortinfoId: "sunday-river",
  },
  {
    name: "Saddleback",
    state: "ME",
    lat: 44.9397,
    lon: -70.5039,
    websiteUrl: "https://www.saddlebackmaine.com",
    skiresortinfoId: "saddleback",
  },
  {
    name: "Shawnee Peak",
    state: "ME",
    lat: 44.0636,
    lon: -70.8611,
    websiteUrl: "https://www.shawneepeak.com",
    skiresortinfoId: "shawnee-peak",
  },
  {
    name: "Mt. Abram",
    state: "ME",
    lat: 44.39,
    lon: -70.6814,
    websiteUrl: "https://www.mtabram.com",
    skiresortinfoId: "mt-abram",
  },
  {
    name: "Black Mountain of Maine",
    state: "ME",
    lat: 44.5203,
    lon: -70.42,
    websiteUrl: "https://www.skiblackmountain.org",
    skiresortinfoId: "black-mountain-maine",
  },
  {
    name: "Camden Snow Bowl",
    state: "ME",
    lat: 44.2178,
    lon: -69.0914,
    websiteUrl: "https://camdensnowbowl.com",
    skiresortinfoId: "camden-snow-bowl",
  },
  {
    name: "Lost Valley",
    state: "ME",
    lat: 44.0867,
    lon: -70.1519,
    websiteUrl: "https://www.lostvalleyski.com",
    skiresortinfoId: "lost-valley",
  },
  {
    name: "Titcomb Mountain",
    state: "ME",
    lat: 44.6611,
    lon: -70.215,
    websiteUrl: "https://www.titcombmountain.com",
    skiresortinfoId: "titcomb-mountain",
  },
  {
    name: "Big Rock",
    state: "ME",
    lat: 46.6933,
    lon: -68.0392,
    websiteUrl: "https://www.bigrockmaine.com",
    skiresortinfoId: "big-rock",
  },

  // ============================================================
  // NEW YORK (Northeast) - 50 resorts
  // ============================================================
  {
    name: "Whiteface",
    state: "NY",
    lat: 44.3658,
    lon: -73.9028,
    websiteUrl: "https://www.whiteface.com",
    skiresortinfoId: "whiteface-lake-placid",
  },
  {
    name: "Gore Mountain",
    state: "NY",
    lat: 43.6772,
    lon: -74.005,
    websiteUrl: "https://www.goremountain.com",
    skiresortinfoId: "gore-mountain",
  },
  {
    name: "Hunter Mountain",
    state: "NY",
    lat: 42.2036,
    lon: -74.2228,
    websiteUrl: "https://www.huntermtn.com",
    skiresortinfoId: "hunter-mountain",
  },
  {
    name: "Windham Mountain",
    state: "NY",
    lat: 42.2975,
    lon: -74.2572,
    websiteUrl: "https://www.windhammountain.com",
    skiresortinfoId: "windham-mountain",
  },
  {
    name: "Belleayre",
    state: "NY",
    lat: 42.1364,
    lon: -74.5022,
    websiteUrl: "https://www.belleayre.com",
    skiresortinfoId: "belleayre",
  },
  {
    name: "Holiday Valley",
    state: "NY",
    lat: 42.2622,
    lon: -78.6683,
    websiteUrl: "https://www.holidayvalley.com",
    skiresortinfoId: "holiday-valley",
  },
  {
    name: "Greek Peak",
    state: "NY",
    lat: 42.5011,
    lon: -76.1483,
    websiteUrl: "https://www.greekpeak.net",
    skiresortinfoId: "greek-peak",
  },
  {
    name: "Bristol Mountain",
    state: "NY",
    lat: 42.7364,
    lon: -77.4033,
    websiteUrl: "https://www.bristolmountain.com",
    skiresortinfoId: "bristol-mountain",
  },
  {
    name: "Peek'n Peak",
    state: "NY",
    lat: 42.0614,
    lon: -79.7386,
    websiteUrl: "https://www.pknpk.com",
    skiresortinfoId: "peeknpeak",
  },
  {
    name: "Titus Mountain",
    state: "NY",
    lat: 44.6814,
    lon: -74.2539,
    websiteUrl: "https://www.titusmountain.com",
    skiresortinfoId: "titus-mountain",
  },
  {
    name: "Snow Ridge",
    state: "NY",
    lat: 43.4878,
    lon: -75.4267,
    websiteUrl: "https://www.snowridge.com",
    skiresortinfoId: "snow-ridge",
  },
  {
    name: "Plattekill Mountain",
    state: "NY",
    lat: 42.2853,
    lon: -74.6367,
    websiteUrl: "https://www.plattekill.com",
    skiresortinfoId: "plattekill-mountain",
  },
  {
    name: "West Mountain",
    state: "NY",
    lat: 43.285,
    lon: -73.8094,
    websiteUrl: "https://www.westmountain.com",
    skiresortinfoId: "west-mountain",
  },
  {
    name: "McCauley Mountain",
    state: "NY",
    lat: 43.5614,
    lon: -75.0089,
    websiteUrl: "https://www.mccauleyny.com",
    skiresortinfoId: "mccauley-mountain",
  },
  {
    name: "Catamount",
    state: "NY",
    lat: 42.1667,
    lon: -73.4664,
    websiteUrl: "https://catamountski.com",
    skiresortinfoId: "catamount",
  },
  {
    name: "Swain",
    state: "NY",
    lat: 42.4822,
    lon: -77.9039,
    websiteUrl: "https://www.swain.com",
    skiresortinfoId: "swain",
  },
  {
    name: "Song Mountain",
    state: "NY",
    lat: 42.8214,
    lon: -76.1417,
    websiteUrl: "https://www.songmountain.com",
    skiresortinfoId: "song-mountain",
  },
  {
    name: "Kissing Bridge",
    state: "NY",
    lat: 42.6042,
    lon: -78.6808,
    websiteUrl: "https://www.kbski.com",
    skiresortinfoId: "kissing-bridge",
  },
  {
    name: "Toggenburg Mountain",
    state: "NY",
    lat: 42.8258,
    lon: -75.9639,
    websiteUrl: "https://www.skitog.com",
    skiresortinfoId: "toggenburg-mountain",
  },
  {
    name: "Labrador Mountain",
    state: "NY",
    lat: 42.8147,
    lon: -76.0431,
    websiteUrl: "https://www.labradormtn.com",
    skiresortinfoId: "labrador-mountain",
  },
  {
    name: "Willard Mountain",
    state: "NY",
    lat: 43.0736,
    lon: -73.3847,
    websiteUrl: "https://www.willardmountain.com",
    skiresortinfoId: "willard-mountain",
  },
  {
    name: "Royal Mountain",
    state: "NY",
    lat: 43.1297,
    lon: -74.6139,
    websiteUrl: "https://www.royalmountain.com",
    skiresortinfoId: "royal-mountain",
  },
  {
    name: "Thunder Ridge",
    state: "NY",
    lat: 41.5111,
    lon: -73.6189,
    websiteUrl: "https://www.thunderridgeski.com",
    skiresortinfoId: "thunder-ridge",
  },
  {
    name: "Mount Peter",
    state: "NY",
    lat: 41.2206,
    lon: -74.3061,
    websiteUrl: "https://www.mtpeter.com",
    skiresortinfoId: "mount-peter",
  },
  {
    name: "Maple Ski Ridge",
    state: "NY",
    lat: 42.8536,
    lon: -74.0539,
    websiteUrl: "https://www.mapleskiridge.com",
    skiresortinfoId: "maple-ski-ridge",
  },
  {
    name: "Oak Mountain",
    state: "NY",
    lat: 43.4633,
    lon: -74.3822,
    websiteUrl: "https://www.oakmountainski.com",
    skiresortinfoId: "oak-mountain",
  },
  {
    name: "Dry Hill",
    state: "NY",
    lat: 43.7989,
    lon: -75.8633,
    websiteUrl: "https://www.dryhillskiarea.com",
    skiresortinfoId: "dry-hill",
  },
  {
    name: "Big Tupper",
    state: "NY",
    lat: 44.2561,
    lon: -74.4467,
    websiteUrl: "https://www.bigtupper.com",
    skiresortinfoId: "big-tupper",
  },
  {
    name: "Woods Valley",
    state: "NY",
    lat: 43.3214,
    lon: -75.2867,
    websiteUrl: "https://www.woodsvalleyskiarea.com",
    skiresortinfoId: "woods-valley",
  },
  {
    name: "Four Seasons",
    state: "NY",
    lat: 42.2358,
    lon: -78.0014,
    websiteUrl: "https://www.fourseasonsgolfandski.com",
    skiresortinfoId: "four-seasons",
  },
  {
    name: "Brantling",
    state: "NY",
    lat: 42.9894,
    lon: -77.5847,
    websiteUrl: "https://www.brantling.com",
    skiresortinfoId: "brantling",
  },
  {
    name: "Hunt Hollow",
    state: "NY",
    lat: 42.5314,
    lon: -77.3378,
    websiteUrl: "https://www.hunthollow.com",
    skiresortinfoId: "hunt-hollow",
  },
  {
    name: "Cockaigne",
    state: "NY",
    lat: 42.2514,
    lon: -79.0206,
    websiteUrl: "https://www.cockaigne.com",
    skiresortinfoId: "cockaigne",
  },
  {
    name: "Mt Van Hoevenberg",
    state: "NY",
    lat: 44.2628,
    lon: -73.93,
    websiteUrl: "https://www.whiteface.com/xc-skiing",
    skiresortinfoId: "mt-van-hoevenberg",
  },
  {
    name: "Camillus Ski Association",
    state: "NY",
    lat: 43.0386,
    lon: -76.3158,
    websiteUrl: "https://camillusskiarea.com",
    skiresortinfoId: "camillus-ski",
  },
  {
    name: "Bousquet",
    state: "MA",
    lat: 42.4475,
    lon: -73.2456,
    websiteUrl: "https://www.bousquets.com",
    skiresortinfoId: "bousquet",
  },
  {
    name: "Jiminy Peak",
    state: "MA",
    lat: 42.5456,
    lon: -73.3689,
    websiteUrl: "https://www.jiminypeak.com",
    skiresortinfoId: "jiminy-peak",
  },
  {
    name: "Wachusett Mountain",
    state: "MA",
    lat: 42.4986,
    lon: -71.8892,
    websiteUrl: "https://www.wachusett.com",
    skiresortinfoId: "wachusett-mountain",
  },
  {
    name: "Berkshire East",
    state: "MA",
    lat: 42.6242,
    lon: -72.8439,
    websiteUrl: "https://www.berkshireeast.com",
    skiresortinfoId: "berkshire-east",
  },
  {
    name: "Ski Butternut",
    state: "MA",
    lat: 42.1819,
    lon: -73.3028,
    websiteUrl: "https://www.skibutternut.com",
    skiresortinfoId: "ski-butternut",
  },
  {
    name: "Blue Hills",
    state: "MA",
    lat: 42.215,
    lon: -71.0883,
    websiteUrl: "https://www.bluehillsreservation.com",
    skiresortinfoId: "blue-hills",
  },
  {
    name: "Nashoba Valley",
    state: "MA",
    lat: 42.5269,
    lon: -71.4467,
    websiteUrl: "https://www.skinashoba.com",
    skiresortinfoId: "nashoba-valley",
  },
  {
    name: "Ski Ward",
    state: "MA",
    lat: 42.3125,
    lon: -71.8075,
    websiteUrl: "https://www.skiward.com",
    skiresortinfoId: "ski-ward",
  },
  {
    name: "Otis Ridge",
    state: "MA",
    lat: 42.2014,
    lon: -73.0789,
    websiteUrl: "https://www.otisridge.com",
    skiresortinfoId: "otis-ridge",
  },
  {
    name: "Mohawk Mountain",
    state: "CT",
    lat: 41.8442,
    lon: -73.3,
    websiteUrl: "https://www.mohawkmtn.com",
    skiresortinfoId: "mohawk-mountain",
  },
  {
    name: "Mount Southington",
    state: "CT",
    lat: 41.5975,
    lon: -72.9042,
    websiteUrl: "https://www.mountsouthington.com",
    skiresortinfoId: "mount-southington",
  },
  {
    name: "Powder Ridge",
    state: "CT",
    lat: 41.5058,
    lon: -72.7128,
    websiteUrl: "https://www.powderridgepark.com",
    skiresortinfoId: "powder-ridge",
  },
  {
    name: "Ski Sundown",
    state: "CT",
    lat: 41.9192,
    lon: -72.9222,
    websiteUrl: "https://www.skisundown.com",
    skiresortinfoId: "ski-sundown",
  },
  {
    name: "Mountain Creek",
    state: "NJ",
    lat: 41.1922,
    lon: -74.5011,
    websiteUrl: "https://www.mountaincreek.com",
    skiresortinfoId: "mountain-creek",
  },
  {
    name: "Big Snow American Dream",
    state: "NJ",
    lat: 40.8134,
    lon: -74.0731,
    websiteUrl: "https://www.bigsnowamericandream.com",
    skiresortinfoId: "big-snow-american-dream",
  },

  // ============================================================
  // PENNSYLVANIA (Northeast) - 21 resorts
  // ============================================================
  {
    name: "Seven Springs",
    state: "PA",
    lat: 40.0228,
    lon: -79.2978,
    websiteUrl: "https://www.7springs.com",
    skiresortinfoId: "seven-springs",
  },
  {
    name: "Blue Mountain",
    state: "PA",
    lat: 40.8228,
    lon: -75.5128,
    websiteUrl: "https://www.skibluemt.com",
    skiresortinfoId: "blue-mountain-pa",
  },
  {
    name: "Camelback",
    state: "PA",
    lat: 41.0522,
    lon: -75.3606,
    websiteUrl: "https://www.camelbackresort.com",
    skiresortinfoId: "camelback",
  },
  {
    name: "Jack Frost",
    state: "PA",
    lat: 41.1372,
    lon: -75.4586,
    websiteUrl: "https://www.jfbb.com",
    skiresortinfoId: "jack-frost",
  },
  {
    name: "Big Boulder",
    state: "PA",
    lat: 41.1039,
    lon: -75.5419,
    websiteUrl: "https://www.jfbb.com",
    skiresortinfoId: "big-boulder",
  },
  {
    name: "Elk Mountain",
    state: "PA",
    lat: 41.6792,
    lon: -75.5803,
    websiteUrl: "https://www.elkskier.com",
    skiresortinfoId: "elk-mountain",
  },
  {
    name: "Bear Creek",
    state: "PA",
    lat: 40.6489,
    lon: -75.6306,
    websiteUrl: "https://www.bcmountainresort.com",
    skiresortinfoId: "bear-creek-pa",
  },
  {
    name: "Shawnee Mountain",
    state: "PA",
    lat: 41.0158,
    lon: -75.0642,
    websiteUrl: "https://www.shawneemt.com",
    skiresortinfoId: "shawnee-mountain",
  },
  {
    name: "Ski Big Bear",
    state: "PA",
    lat: 41.1239,
    lon: -75.5367,
    websiteUrl: "https://www.skibigbear.com",
    skiresortinfoId: "ski-big-bear",
  },
  {
    name: "Laurel Mountain",
    state: "PA",
    lat: 40.1667,
    lon: -79.1658,
    websiteUrl: "https://www.laurelmountainski.com",
    skiresortinfoId: "laurel-mountain",
  },
  {
    name: "Hidden Valley",
    state: "PA",
    lat: 40.0556,
    lon: -79.2503,
    websiteUrl: "https://www.hiddenvalleyresort.com",
    skiresortinfoId: "hidden-valley-pa",
  },
  {
    name: "Whitetail",
    state: "PA",
    lat: 39.7411,
    lon: -77.9319,
    websiteUrl: "https://www.skiwhitetail.com",
    skiresortinfoId: "whitetail",
  },
  {
    name: "Liberty Mountain",
    state: "PA",
    lat: 39.7622,
    lon: -77.3714,
    websiteUrl: "https://www.skiliberty.com",
    skiresortinfoId: "liberty-mountain",
  },
  {
    name: "Roundtop Mountain",
    state: "PA",
    lat: 40.1086,
    lon: -76.9236,
    websiteUrl: "https://www.skiroundtop.com",
    skiresortinfoId: "roundtop-mountain",
  },
  {
    name: "Tussey Mountain",
    state: "PA",
    lat: 40.7519,
    lon: -77.7597,
    websiteUrl: "https://www.tusseymountain.com",
    skiresortinfoId: "tussey-mountain",
  },
  {
    name: "Spring Mountain",
    state: "PA",
    lat: 40.2772,
    lon: -75.4508,
    websiteUrl: "https://www.springmountainadventures.com",
    skiresortinfoId: "spring-mountain",
  },
  {
    name: "Mount Pleasant of Edinboro",
    state: "PA",
    lat: 41.8592,
    lon: -80.1156,
    websiteUrl: "https://www.edinborolakeresort.com",
    skiresortinfoId: "mount-pleasant-edinboro",
  },
  {
    name: "Boyce Park",
    state: "PA",
    lat: 40.4461,
    lon: -79.7469,
    websiteUrl: "https://www.alleghenycounty.us/parks/boyce-park",
    skiresortinfoId: "boyce-park",
  },
  {
    name: "Montage Mountain",
    state: "PA",
    lat: 41.3583,
    lon: -75.6894,
    websiteUrl: "https://www.montagemountainresorts.com",
    skiresortinfoId: "montage-mountain",
  },
  {
    name: "Mystic Mountain at Nemacolin",
    state: "PA",
    lat: 39.8306,
    lon: -79.6097,
    websiteUrl: "https://www.nemacolin.com",
    skiresortinfoId: "mystic-mountain",
  },
  {
    name: "Ski Sawmill",
    state: "PA",
    lat: 41.5403,
    lon: -77.3875,
    websiteUrl: "https://www.skisawmill.com",
    skiresortinfoId: "ski-sawmill",
  },

  // ============================================================
  // MONTANA (Rockies) - 16 resorts
  // ============================================================
  {
    name: "Big Sky",
    state: "MT",
    lat: 45.2858,
    lon: -111.4008,
    websiteUrl: "https://www.bigskyresort.com",
    skiresortinfoId: "big-sky",
  },
  {
    name: "Whitefish Mountain",
    state: "MT",
    lat: 48.4817,
    lon: -114.3522,
    websiteUrl: "https://skiwhitefish.com",
    skiresortinfoId: "whitefish-mountain",
  },
  {
    name: "Bridger Bowl",
    state: "MT",
    lat: 45.8181,
    lon: -110.8972,
    websiteUrl: "https://www.bridgerbowl.com",
    skiresortinfoId: "bridger-bowl",
  },
  {
    name: "Red Lodge Mountain",
    state: "MT",
    lat: 45.1833,
    lon: -109.3408,
    websiteUrl: "https://www.redlodgemountain.com",
    skiresortinfoId: "red-lodge-mountain",
  },
  {
    name: "Montana Snowbowl",
    state: "MT",
    lat: 46.9333,
    lon: -114.1722,
    websiteUrl: "https://www.montanasnowbowl.com",
    skiresortinfoId: "montana-snowbowl",
  },
  {
    name: "Discovery Ski Area",
    state: "MT",
    lat: 46.2486,
    lon: -113.2361,
    websiteUrl: "https://www.skidiscovery.com",
    skiresortinfoId: "discovery-ski-area",
  },
  {
    name: "Lost Trail Powder Mountain",
    state: "MT",
    lat: 45.6942,
    lon: -113.95,
    websiteUrl: "https://www.losttrail.com",
    skiresortinfoId: "lost-trail",
  },
  {
    name: "Great Divide",
    state: "MT",
    lat: 46.7472,
    lon: -112.3089,
    websiteUrl: "https://www.skigd.com",
    skiresortinfoId: "great-divide",
  },
  {
    name: "Maverick Mountain",
    state: "MT",
    lat: 45.45,
    lon: -113.0167,
    websiteUrl: "https://www.skimaverick.com",
    skiresortinfoId: "maverick-mountain",
  },
  {
    name: "Teton Pass Ski Area",
    state: "MT",
    lat: 47.8389,
    lon: -112.3083,
    websiteUrl: "https://www.tetonpassresort.com",
    skiresortinfoId: "teton-pass",
  },
  {
    name: "Lookout Pass",
    state: "MT",
    lat: 47.4553,
    lon: -115.6719,
    websiteUrl: "https://www.skilookout.com",
    skiresortinfoId: "lookout-pass",
  },
  {
    name: "Showdown",
    state: "MT",
    lat: 46.85,
    lon: -110.7167,
    websiteUrl: "https://www.showdownmontana.com",
    skiresortinfoId: "showdown",
  },
  {
    name: "Bear Paw Ski Bowl",
    state: "MT",
    lat: 48.2583,
    lon: -109.9056,
    websiteUrl: "https://www.skibearpaw.com",
    skiresortinfoId: "bear-paw",
  },
  {
    name: "Turner Mountain",
    state: "MT",
    lat: 48.7217,
    lon: -115.585,
    websiteUrl: "https://www.skiturner.com",
    skiresortinfoId: "turner-mountain",
  },
  {
    name: "Blacktail Mountain",
    state: "MT",
    lat: 48.0167,
    lon: -114.3667,
    websiteUrl: "https://www.blacktailmountain.com",
    skiresortinfoId: "blacktail-mountain",
  },
  {
    name: "Yellowstone Club",
    state: "MT",
    lat: 45.25,
    lon: -111.3833,
    websiteUrl: "https://www.yellowstoneclub.com",
    skiresortinfoId: "yellowstone-club",
  },

  // ============================================================
  // IDAHO (Rockies) - 15 resorts
  // ============================================================
  {
    name: "Sun Valley",
    state: "ID",
    lat: 43.6975,
    lon: -114.3522,
    websiteUrl: "https://www.sunvalley.com",
    skiresortinfoId: "sun-valley",
  },
  {
    name: "Schweitzer",
    state: "ID",
    lat: 48.3683,
    lon: -116.6217,
    websiteUrl: "https://www.schweitzer.com",
    skiresortinfoId: "schweitzer",
  },
  {
    name: "Tamarack",
    state: "ID",
    lat: 44.7483,
    lon: -116.1267,
    websiteUrl: "https://www.tamarackidaho.com",
    skiresortinfoId: "tamarack",
  },
  {
    name: "Bogus Basin",
    state: "ID",
    lat: 43.7647,
    lon: -116.1019,
    websiteUrl: "https://www.bogusbasin.org",
    skiresortinfoId: "bogus-basin",
  },
  {
    name: "Brundage Mountain",
    state: "ID",
    lat: 45.0461,
    lon: -116.1417,
    websiteUrl: "https://www.brundage.com",
    skiresortinfoId: "brundage-mountain",
  },
  {
    name: "Silver Mountain",
    state: "ID",
    lat: 47.5417,
    lon: -116.1283,
    websiteUrl: "https://www.silvermt.com",
    skiresortinfoId: "silver-mountain",
  },
  {
    name: "Pebble Creek",
    state: "ID",
    lat: 42.7417,
    lon: -112.1167,
    websiteUrl: "https://www.pebblecreekskiarea.com",
    skiresortinfoId: "pebble-creek",
  },
  {
    name: "Soldier Mountain",
    state: "ID",
    lat: 43.675,
    lon: -114.7833,
    websiteUrl: "https://www.soldiermountain.com",
    skiresortinfoId: "soldier-mountain",
  },
  {
    name: "Magic Mountain",
    state: "ID",
    lat: 43.0833,
    lon: -114.2667,
    websiteUrl: "https://www.magicmountainresort.com",
    skiresortinfoId: "magic-mountain-id",
  },
  {
    name: "Pomerelle",
    state: "ID",
    lat: 42.2333,
    lon: -113.6333,
    websiteUrl: "https://www.pomerelle.com",
    skiresortinfoId: "pomerelle",
  },
  {
    name: "Kelly Canyon",
    state: "ID",
    lat: 43.65,
    lon: -111.5833,
    websiteUrl: "https://www.kellycanyon.com",
    skiresortinfoId: "kelly-canyon",
  },
  {
    name: "Lookout Pass",
    state: "ID",
    lat: 47.4553,
    lon: -115.6719,
    websiteUrl: "https://www.skilookout.com",
    skiresortinfoId: "lookout-pass-id",
  },
  {
    name: "Cottonwood Butte",
    state: "ID",
    lat: 45.95,
    lon: -116.3833,
    websiteUrl: "https://www.cottonwoodbutte.org",
    skiresortinfoId: "cottonwood-butte",
  },
  {
    name: "Little Ski Hill",
    state: "ID",
    lat: 44.4167,
    lon: -116.0833,
    websiteUrl: "https://www.littleskihill.org",
    skiresortinfoId: "little-ski-hill",
  },
  {
    name: "Snowhaven",
    state: "ID",
    lat: 43.5167,
    lon: -116.45,
    websiteUrl: "https://www.snowhaven.org",
    skiresortinfoId: "snowhaven",
  },

  // ============================================================
  // WYOMING (Rockies) - 8 resorts
  // ============================================================
  {
    name: "Jackson Hole",
    state: "WY",
    lat: 43.5875,
    lon: -110.8278,
    websiteUrl: "https://www.jacksonhole.com",
    skiresortinfoId: "jackson-hole",
  },
  {
    name: "Grand Targhee",
    state: "WY",
    lat: 43.7872,
    lon: -110.9586,
    websiteUrl: "https://www.grandtarghee.com",
    skiresortinfoId: "grand-targhee",
  },
  {
    name: "Snow King",
    state: "WY",
    lat: 43.4722,
    lon: -110.7536,
    websiteUrl: "https://www.snowkingmountain.com",
    skiresortinfoId: "snow-king",
  },
  {
    name: "White Pine Ski Area",
    state: "WY",
    lat: 42.8833,
    lon: -109.7667,
    websiteUrl: "https://www.whitepineski.com",
    skiresortinfoId: "white-pine",
  },
  {
    name: "Snowy Range",
    state: "WY",
    lat: 41.3333,
    lon: -106.1333,
    websiteUrl: "https://www.snowyrangeski.com",
    skiresortinfoId: "snowy-range",
  },
  {
    name: "Hogadon",
    state: "WY",
    lat: 42.8833,
    lon: -106.2833,
    websiteUrl: "https://www.hogadon.net",
    skiresortinfoId: "hogadon",
  },
  {
    name: "Sleeping Giant",
    state: "WY",
    lat: 44.4833,
    lon: -109.8833,
    websiteUrl: "https://www.skisg.com",
    skiresortinfoId: "sleeping-giant",
  },
  {
    name: "Pine Creek",
    state: "WY",
    lat: 44.5833,
    lon: -108.0167,
    websiteUrl: "https://www.pinecreekski.com",
    skiresortinfoId: "pine-creek",
  },

  // ============================================================
  // WASHINGTON (West) - 20 resorts
  // ============================================================
  {
    name: "Crystal Mountain",
    state: "WA",
    lat: 46.9283,
    lon: -121.5044,
    websiteUrl: "https://www.crystalmountainresort.com",
    skiresortinfoId: "crystal-mountain-wa",
  },
  {
    name: "Stevens Pass",
    state: "WA",
    lat: 47.7456,
    lon: -121.0892,
    websiteUrl: "https://www.stevenspass.com",
    skiresortinfoId: "stevens-pass",
  },
  {
    name: "Summit at Snoqualmie",
    state: "WA",
    lat: 47.4208,
    lon: -121.4142,
    websiteUrl: "https://www.summitatsnoqualmie.com",
    skiresortinfoId: "summit-at-snoqualmie",
  },
  {
    name: "Mt. Baker",
    state: "WA",
    lat: 48.8575,
    lon: -121.6642,
    websiteUrl: "https://www.mtbaker.us",
    skiresortinfoId: "mt-baker",
  },
  {
    name: "White Pass",
    state: "WA",
    lat: 46.6383,
    lon: -121.3908,
    websiteUrl: "https://skiwhitepass.com",
    skiresortinfoId: "white-pass",
  },
  {
    name: "Mission Ridge",
    state: "WA",
    lat: 47.2925,
    lon: -120.4,
    websiteUrl: "https://www.missionridge.com",
    skiresortinfoId: "mission-ridge",
  },
  {
    name: "Mt. Spokane",
    state: "WA",
    lat: 47.925,
    lon: -117.1022,
    websiteUrl: "https://www.mtspokane.com",
    skiresortinfoId: "mt-spokane",
  },
  {
    name: "49 Degrees North",
    state: "WA",
    lat: 48.7983,
    lon: -117.5678,
    websiteUrl: "https://www.ski49n.com",
    skiresortinfoId: "49-degrees-north",
  },
  {
    name: "Bluewood",
    state: "WA",
    lat: 46.0833,
    lon: -117.8333,
    websiteUrl: "https://www.bluewood.com",
    skiresortinfoId: "bluewood",
  },
  {
    name: "Hurricane Ridge",
    state: "WA",
    lat: 47.9667,
    lon: -123.4833,
    websiteUrl: "https://www.hurricaneridge.com",
    skiresortinfoId: "hurricane-ridge",
  },
  {
    name: "Loup Loup",
    state: "WA",
    lat: 48.3917,
    lon: -119.9083,
    websiteUrl: "https://www.skitheloup.com",
    skiresortinfoId: "loup-loup",
  },
  {
    name: "Echo Valley",
    state: "WA",
    lat: 47.4167,
    lon: -120.0833,
    websiteUrl: "https://www.echovalley.com",
    skiresortinfoId: "echo-valley-wa",
  },
  {
    name: "Badger Mountain",
    state: "WA",
    lat: 48.15,
    lon: -119.4167,
    websiteUrl: "https://www.badgermountain.org",
    skiresortinfoId: "badger-mountain",
  },
  {
    name: "Ski Bluewood",
    state: "WA",
    lat: 46.0833,
    lon: -117.8333,
    websiteUrl: "https://www.bluewood.com",
    skiresortinfoId: "ski-bluewood",
  },
  {
    name: "Snoqualmie Summit",
    state: "WA",
    lat: 47.4256,
    lon: -121.4117,
    websiteUrl: "https://www.summitatsnoqualmie.com",
    skiresortinfoId: "snoqualmie-summit",
  },
  {
    name: "Alpental",
    state: "WA",
    lat: 47.4433,
    lon: -121.4283,
    websiteUrl: "https://www.summitatsnoqualmie.com",
    skiresortinfoId: "alpental",
  },
  {
    name: "Summit West",
    state: "WA",
    lat: 47.4267,
    lon: -121.4092,
    websiteUrl: "https://www.summitatsnoqualmie.com",
    skiresortinfoId: "summit-west",
  },
  {
    name: "Summit Central",
    state: "WA",
    lat: 47.4233,
    lon: -121.4142,
    websiteUrl: "https://www.summitatsnoqualmie.com",
    skiresortinfoId: "summit-central",
  },
  {
    name: "Summit East",
    state: "WA",
    lat: 47.4292,
    lon: -121.4061,
    websiteUrl: "https://www.summitatsnoqualmie.com",
    skiresortinfoId: "summit-east",
  },
  {
    name: "Hyak",
    state: "WA",
    lat: 47.3931,
    lon: -121.3767,
    websiteUrl: "https://www.summitatsnoqualmie.com",
    skiresortinfoId: "hyak",
  },

  // ============================================================
  // OREGON (West) - 13 resorts
  // ============================================================
  {
    name: "Mt. Bachelor",
    state: "OR",
    lat: 43.9792,
    lon: -121.6867,
    websiteUrl: "https://www.mtbachelor.com",
    skiresortinfoId: "mt-bachelor",
  },
  {
    name: "Mt. Hood Meadows",
    state: "OR",
    lat: 45.3331,
    lon: -121.6653,
    websiteUrl: "https://www.skihood.com",
    skiresortinfoId: "mt-hood-meadows",
  },
  {
    name: "Timberline Lodge",
    state: "OR",
    lat: 45.3308,
    lon: -121.7111,
    websiteUrl: "https://www.timberlinelodge.com",
    skiresortinfoId: "timberline-lodge",
  },
  {
    name: "Mt. Hood Skibowl",
    state: "OR",
    lat: 45.3,
    lon: -121.7667,
    websiteUrl: "https://www.skibowl.com",
    skiresortinfoId: "mt-hood-skibowl",
  },
  {
    name: "Mt. Ashland",
    state: "OR",
    lat: 42.0822,
    lon: -122.7169,
    websiteUrl: "https://www.mtashland.com",
    skiresortinfoId: "mt-ashland",
  },
  {
    name: "Hoodoo",
    state: "OR",
    lat: 44.4064,
    lon: -121.8722,
    websiteUrl: "https://www.hoodoo.com",
    skiresortinfoId: "hoodoo",
  },
  {
    name: "Willamette Pass",
    state: "OR",
    lat: 43.5967,
    lon: -122.0406,
    websiteUrl: "https://www.willamettepass.com",
    skiresortinfoId: "willamette-pass",
  },
  {
    name: "Anthony Lakes",
    state: "OR",
    lat: 44.95,
    lon: -118.2333,
    websiteUrl: "https://www.anthonylakes.com",
    skiresortinfoId: "anthony-lakes",
  },
  {
    name: "Spout Springs",
    state: "OR",
    lat: 45.8833,
    lon: -118.1333,
    websiteUrl: "https://www.spoutsprings.com",
    skiresortinfoId: "spout-springs",
  },
  {
    name: "Ferguson Ridge",
    state: "OR",
    lat: 45.25,
    lon: -117.4667,
    websiteUrl: "https://www.fergusonridge.com",
    skiresortinfoId: "ferguson-ridge",
  },
  {
    name: "Warner Canyon",
    state: "OR",
    lat: 42.2833,
    lon: -120.2167,
    websiteUrl: "https://www.warnercanyon.org",
    skiresortinfoId: "warner-canyon",
  },
  {
    name: "Cooper Spur",
    state: "OR",
    lat: 45.4167,
    lon: -121.5333,
    websiteUrl: "https://www.cooperspur.com",
    skiresortinfoId: "cooper-spur",
  },
  {
    name: "Summit Ski Area",
    state: "OR",
    lat: 45.2833,
    lon: -121.75,
    websiteUrl: "https://www.summitskiarea.com",
    skiresortinfoId: "summit-ski-area",
  },

  // ============================================================
  // MICHIGAN (Midwest) - 40 resorts
  // ============================================================
  {
    name: "Boyne Mountain",
    state: "MI",
    lat: 45.1675,
    lon: -84.9181,
    websiteUrl: "https://www.boynemountain.com",
    skiresortinfoId: "boyne-mountain",
  },
  {
    name: "Boyne Highlands",
    state: "MI",
    lat: 45.4653,
    lon: -84.9367,
    websiteUrl: "https://www.boynehighlands.com",
    skiresortinfoId: "boyne-highlands",
  },
  {
    name: "Crystal Mountain",
    state: "MI",
    lat: 44.5258,
    lon: -86.055,
    websiteUrl: "https://www.crystalmountain.com",
    skiresortinfoId: "crystal-mountain-mi",
  },
  {
    name: "Nubs Nob",
    state: "MI",
    lat: 45.4725,
    lon: -84.9133,
    websiteUrl: "https://www.nubsnob.com",
    skiresortinfoId: "nubs-nob",
  },
  {
    name: "Mt. Brighton",
    state: "MI",
    lat: 42.5381,
    lon: -83.8239,
    websiteUrl: "https://www.mtbrighton.com",
    skiresortinfoId: "mt-brighton",
  },
  {
    name: "Mount Bohemia",
    state: "MI",
    lat: 47.3833,
    lon: -87.95,
    websiteUrl: "https://www.mtbohemia.com",
    skiresortinfoId: "mount-bohemia",
  },
  {
    name: "Indianhead Mountain",
    state: "MI",
    lat: 46.4583,
    lon: -89.9667,
    websiteUrl: "https://www.indianheadmtn.com",
    skiresortinfoId: "indianhead-mountain",
  },
  {
    name: "Blackjack",
    state: "MI",
    lat: 46.4833,
    lon: -89.9667,
    websiteUrl: "https://www.blackjackski.com",
    skiresortinfoId: "blackjack",
  },
  {
    name: "Big Powderhorn Mountain",
    state: "MI",
    lat: 46.5083,
    lon: -90.0167,
    websiteUrl: "https://www.bigpowderhorn.net",
    skiresortinfoId: "big-powderhorn",
  },
  {
    name: "Ski Brule",
    state: "MI",
    lat: 46.0333,
    lon: -88.3167,
    websiteUrl: "https://www.skibrule.com",
    skiresortinfoId: "ski-brule",
  },
  {
    name: "Marquette Mountain",
    state: "MI",
    lat: 46.5042,
    lon: -87.4458,
    websiteUrl: "https://www.marquettemountain.com",
    skiresortinfoId: "marquette-mountain",
  },
  {
    name: "Pine Mountain",
    state: "MI",
    lat: 45.8167,
    lon: -88.0833,
    websiteUrl: "https://www.pinemountainresort.com",
    skiresortinfoId: "pine-mountain-mi",
  },
  {
    name: "Norway Mountain",
    state: "MI",
    lat: 45.8,
    lon: -87.8833,
    websiteUrl: "https://www.norwaymountain.com",
    skiresortinfoId: "norway-mountain",
  },
  {
    name: "Mont Ripley",
    state: "MI",
    lat: 47.1167,
    lon: -88.4833,
    websiteUrl: "https://www.mtu.edu/mont-ripley",
    skiresortinfoId: "mont-ripley",
  },
  {
    name: "Porcupine Mountains",
    state: "MI",
    lat: 46.8167,
    lon: -89.75,
    websiteUrl: "https://www.porkies.com",
    skiresortinfoId: "porcupine-mountains",
  },
  {
    name: "Shanty Creek",
    state: "MI",
    lat: 44.9,
    lon: -85.1833,
    websiteUrl: "https://www.shantycreek.com",
    skiresortinfoId: "shanty-creek",
  },
  {
    name: "Schuss Mountain",
    state: "MI",
    lat: 44.9167,
    lon: -85.1667,
    websiteUrl: "https://www.shantycreek.com",
    skiresortinfoId: "schuss-mountain",
  },
  {
    name: "Caberfae Peaks",
    state: "MI",
    lat: 44.2539,
    lon: -85.6714,
    websiteUrl: "https://www.caberfaepeaks.com",
    skiresortinfoId: "caberfae-peaks",
  },
  {
    name: "Treetops",
    state: "MI",
    lat: 45.0333,
    lon: -84.6667,
    websiteUrl: "https://www.treetops.com",
    skiresortinfoId: "treetops",
  },
  {
    name: "Mt. Holly",
    state: "MI",
    lat: 42.7933,
    lon: -83.5658,
    websiteUrl: "https://www.skimtholly.com",
    skiresortinfoId: "mt-holly",
  },
  {
    name: "Alpine Valley",
    state: "MI",
    lat: 42.7167,
    lon: -83.6,
    websiteUrl: "https://www.skialpinevalley.com",
    skiresortinfoId: "alpine-valley-mi",
  },
  {
    name: "Pine Knob",
    state: "MI",
    lat: 42.7644,
    lon: -83.3861,
    websiteUrl: "https://www.skipineknob.com",
    skiresortinfoId: "pine-knob",
  },
  {
    name: "Bittersweet",
    state: "MI",
    lat: 42.4,
    lon: -86.0833,
    websiteUrl: "https://www.skibittersweet.com",
    skiresortinfoId: "bittersweet",
  },
  {
    name: "Swiss Valley",
    state: "MI",
    lat: 41.9833,
    lon: -86.0167,
    websiteUrl: "https://www.swissvalleyski.com",
    skiresortinfoId: "swiss-valley",
  },
  {
    name: "Timber Ridge",
    state: "MI",
    lat: 42.45,
    lon: -85.6167,
    websiteUrl: "https://www.timberridgeski.com",
    skiresortinfoId: "timber-ridge",
  },
  {
    name: "Cannonsburg",
    state: "MI",
    lat: 43.0667,
    lon: -85.4833,
    websiteUrl: "https://www.cannonsburg.com",
    skiresortinfoId: "cannonsburg",
  },
  {
    name: "Snow Snake Mountain",
    state: "MI",
    lat: 43.2167,
    lon: -84.3833,
    websiteUrl: "https://www.snowsnake.net",
    skiresortinfoId: "snow-snake-mountain",
  },
  {
    name: "Apple Mountain",
    state: "MI",
    lat: 43.4833,
    lon: -84.15,
    websiteUrl: "https://www.applemountain.com",
    skiresortinfoId: "apple-mountain",
  },
  {
    name: "Mount Zion",
    state: "MI",
    lat: 46.4833,
    lon: -89.9333,
    websiteUrl: "https://www.mtzion.us",
    skiresortinfoId: "mount-zion",
  },
  {
    name: "Otsego Club",
    state: "MI",
    lat: 45.0,
    lon: -84.6667,
    websiteUrl: "https://www.otsegoclub.com",
    skiresortinfoId: "otsego-club",
  },

  // ============================================================
  // WISCONSIN (Midwest) - 30 resorts
  // ============================================================
  {
    name: "Granite Peak",
    state: "WI",
    lat: 44.925,
    lon: -89.6833,
    websiteUrl: "https://www.skigranitepeak.com",
    skiresortinfoId: "granite-peak",
  },
  {
    name: "Devil's Head",
    state: "WI",
    lat: 43.4047,
    lon: -89.8,
    websiteUrl: "https://www.devilsheadresort.com",
    skiresortinfoId: "devils-head",
  },
  {
    name: "Cascade Mountain",
    state: "WI",
    lat: 43.5333,
    lon: -89.7167,
    websiteUrl: "https://www.cascademountain.com",
    skiresortinfoId: "cascade-mountain",
  },
  {
    name: "Trollhaugen",
    state: "WI",
    lat: 45.3833,
    lon: -92.65,
    websiteUrl: "https://www.trollhaugen.com",
    skiresortinfoId: "trollhaugen",
  },
  {
    name: "Alpine Valley",
    state: "WI",
    lat: 42.675,
    lon: -88.4833,
    websiteUrl: "https://www.alpinevalleyresort.com",
    skiresortinfoId: "alpine-valley-wi",
  },
  {
    name: "Whitecap Mountain",
    state: "WI",
    lat: 46.4167,
    lon: -90.1833,
    websiteUrl: "https://www.whitecapresort.com",
    skiresortinfoId: "whitecap-mountain",
  },
  {
    name: "Grand Geneva",
    state: "WI",
    lat: 42.5833,
    lon: -88.4833,
    websiteUrl: "https://www.grandgeneva.com",
    skiresortinfoId: "grand-geneva",
  },
  {
    name: "Hidden Valley",
    state: "WI",
    lat: 44.5,
    lon: -88.0833,
    websiteUrl: "https://www.hvski.com",
    skiresortinfoId: "hidden-valley-wi",
  },
  {
    name: "Mt. La Crosse",
    state: "WI",
    lat: 43.7833,
    lon: -91.2833,
    websiteUrl: "https://www.mtlacrosse.com",
    skiresortinfoId: "mt-la-crosse",
  },
  {
    name: "Tyrol Basin",
    state: "WI",
    lat: 43.1167,
    lon: -89.7333,
    websiteUrl: "https://www.tyrolbasin.com",
    skiresortinfoId: "tyrol-basin",
  },
  {
    name: "Bruce Mound",
    state: "WI",
    lat: 44.4667,
    lon: -90.5833,
    websiteUrl: "https://www.brucemound.com",
    skiresortinfoId: "bruce-mound",
  },
  {
    name: "Little Switzerland",
    state: "WI",
    lat: 43.3667,
    lon: -90.8333,
    websiteUrl: "https://www.littleswitz.com",
    skiresortinfoId: "little-switzerland",
  },
  {
    name: "Sunburst",
    state: "WI",
    lat: 43.5,
    lon: -88.0833,
    websiteUrl: "https://www.sunburstwi.com",
    skiresortinfoId: "sunburst",
  },
  {
    name: "Christie Mountain",
    state: "WI",
    lat: 45.4833,
    lon: -91.3833,
    websiteUrl: "https://www.christiemountain.com",
    skiresortinfoId: "christie-mountain",
  },
  {
    name: "Nordic Mountain",
    state: "WI",
    lat: 44.15,
    lon: -89.15,
    websiteUrl: "https://www.nordicmountain.com",
    skiresortinfoId: "nordic-mountain",
  },
  {
    name: "Christmas Mountain",
    state: "WI",
    lat: 43.5333,
    lon: -89.8,
    websiteUrl: "https://www.christmasmountainvillage.com",
    skiresortinfoId: "christmas-mountain",
  },
  {
    name: "Wilmot Mountain",
    state: "WI",
    lat: 42.5,
    lon: -88.2,
    websiteUrl: "https://www.wilmotmountain.com",
    skiresortinfoId: "wilmot-mountain",
  },
  {
    name: "Mount Ashwabay",
    state: "WI",
    lat: 46.75,
    lon: -90.9,
    websiteUrl: "https://www.mtashwabay.org",
    skiresortinfoId: "mount-ashwabay",
  },
  {
    name: "Highlands of Olympia",
    state: "WI",
    lat: 44.3,
    lon: -88.0833,
    websiteUrl: "https://www.highlandsofolympia.com",
    skiresortinfoId: "highlands-of-olympia",
  },
  {
    name: "Ausblick",
    state: "WI",
    lat: 43.2167,
    lon: -88.4167,
    websiteUrl: "https://www.ausblickskiclub.com",
    skiresortinfoId: "ausblick",
  },
  {
    name: "Sky Line",
    state: "WI",
    lat: 43.3333,
    lon: -89.5833,
    websiteUrl: "https://www.skylinegolfandski.com",
    skiresortinfoId: "sky-line",
  },

  // ============================================================
  // MINNESOTA (Midwest) - 15 resorts
  // ============================================================
  {
    name: "Lutsen Mountains",
    state: "MN",
    lat: 47.6333,
    lon: -90.7167,
    websiteUrl: "https://www.lutsen.com",
    skiresortinfoId: "lutsen-mountains",
  },
  {
    name: "Spirit Mountain",
    state: "MN",
    lat: 46.7167,
    lon: -92.2167,
    websiteUrl: "https://www.spiritmt.com",
    skiresortinfoId: "spirit-mountain",
  },
  {
    name: "Afton Alps",
    state: "MN",
    lat: 44.85,
    lon: -92.7833,
    websiteUrl: "https://www.aftonalps.com",
    skiresortinfoId: "afton-alps",
  },
  {
    name: "Welch Village",
    state: "MN",
    lat: 44.5667,
    lon: -92.7167,
    websiteUrl: "https://www.welchvillage.com",
    skiresortinfoId: "welch-village",
  },
  {
    name: "Wild Mountain",
    state: "MN",
    lat: 45.4333,
    lon: -92.75,
    websiteUrl: "https://www.wildmountain.com",
    skiresortinfoId: "wild-mountain",
  },
  {
    name: "Giants Ridge",
    state: "MN",
    lat: 47.5167,
    lon: -92.45,
    websiteUrl: "https://www.giantsridge.com",
    skiresortinfoId: "giants-ridge",
  },
  {
    name: "Buena Vista",
    state: "MN",
    lat: 46.3833,
    lon: -94.3667,
    websiteUrl: "https://www.buenavistaskiarea.com",
    skiresortinfoId: "buena-vista",
  },
  {
    name: "Mount Kato",
    state: "MN",
    lat: 44.1333,
    lon: -93.9667,
    websiteUrl: "https://www.mountkato.com",
    skiresortinfoId: "mount-kato",
  },
  {
    name: "Hyland Hills",
    state: "MN",
    lat: 44.85,
    lon: -93.4,
    websiteUrl: "https://www.threeriverspd.org/hyland",
    skiresortinfoId: "hyland-hills",
  },
  {
    name: "Buck Hill",
    state: "MN",
    lat: 44.7167,
    lon: -93.2833,
    websiteUrl: "https://www.buckhill.com",
    skiresortinfoId: "buck-hill",
  },
  {
    name: "Andes Tower Hills",
    state: "MN",
    lat: 45.8833,
    lon: -95.3333,
    websiteUrl: "https://www.andestowerhills.com",
    skiresortinfoId: "andes-tower-hills",
  },
  {
    name: "Coffee Mill",
    state: "MN",
    lat: 44.45,
    lon: -91.95,
    websiteUrl: "https://www.coffeemillskiarea.com",
    skiresortinfoId: "coffee-mill",
  },
  {
    name: "Powder Ridge",
    state: "MN",
    lat: 45.2667,
    lon: -94.1833,
    websiteUrl: "https://www.powderridge.com",
    skiresortinfoId: "powder-ridge-mn",
  },
  {
    name: "Trollhaugen",
    state: "MN",
    lat: 45.3833,
    lon: -92.65,
    websiteUrl: "https://www.trollhaugen.com",
    skiresortinfoId: "trollhaugen-mn",
  },
  {
    name: "Quadna Mountain",
    state: "MN",
    lat: 46.65,
    lon: -93.55,
    websiteUrl: "https://www.quadna.com",
    skiresortinfoId: "quadna-mountain",
  },

  // ============================================================
  // WEST VIRGINIA (Southeast) - 4 resorts
  // ============================================================
  {
    name: "Snowshoe Mountain",
    state: "WV",
    lat: 38.4069,
    lon: -79.9939,
    websiteUrl: "https://www.snowshoemtn.com",
    skiresortinfoId: "snowshoe-mountain",
  },
  {
    name: "Winterplace",
    state: "WV",
    lat: 37.5733,
    lon: -81.0747,
    websiteUrl: "https://www.winterplace.com",
    skiresortinfoId: "winterplace",
  },
  {
    name: "Canaan Valley",
    state: "WV",
    lat: 38.9889,
    lon: -79.4261,
    websiteUrl: "https://www.canaanresort.com",
    skiresortinfoId: "canaan-valley",
  },
  {
    name: "Timberline Mountain",
    state: "WV",
    lat: 39.0028,
    lon: -79.3944,
    websiteUrl: "https://www.timberlinemountain.com",
    skiresortinfoId: "timberline-mountain",
  },

  // ============================================================
  // NORTH CAROLINA (Southeast) - 5 resorts
  // ============================================================
  {
    name: "Sugar Mountain",
    state: "NC",
    lat: 36.1186,
    lon: -81.8733,
    websiteUrl: "https://www.skisugar.com",
    skiresortinfoId: "sugar-mountain",
  },
  {
    name: "Beech Mountain",
    state: "NC",
    lat: 36.1833,
    lon: -81.8833,
    websiteUrl: "https://www.beechmountainresort.com",
    skiresortinfoId: "beech-mountain",
  },
  {
    name: "Appalachian Ski Mountain",
    state: "NC",
    lat: 36.0897,
    lon: -81.5839,
    websiteUrl: "https://www.appskimtn.com",
    skiresortinfoId: "appalachian-ski-mountain",
  },
  {
    name: "Cataloochee",
    state: "NC",
    lat: 35.4828,
    lon: -83.0853,
    websiteUrl: "https://www.cataloochee.com",
    skiresortinfoId: "cataloochee",
  },
  {
    name: "Sapphire Valley",
    state: "NC",
    lat: 35.1167,
    lon: -83.0667,
    websiteUrl: "https://www.skisapphirevalley.com",
    skiresortinfoId: "sapphire-valley",
  },

  // ============================================================
  // VIRGINIA (Southeast) - 4 resorts
  // ============================================================
  {
    name: "Wintergreen",
    state: "VA",
    lat: 37.9322,
    lon: -78.9056,
    websiteUrl: "https://www.wintergreenresort.com",
    skiresortinfoId: "wintergreen",
  },
  {
    name: "Massanutten",
    state: "VA",
    lat: 38.4083,
    lon: -78.7667,
    websiteUrl: "https://www.massresort.com",
    skiresortinfoId: "massanutten",
  },
  {
    name: "Bryce Resort",
    state: "VA",
    lat: 38.8372,
    lon: -78.8572,
    websiteUrl: "https://www.bryceresort.com",
    skiresortinfoId: "bryce-resort",
  },
  {
    name: "The Omni Homestead",
    state: "VA",
    lat: 37.9978,
    lon: -79.8306,
    websiteUrl: "https://www.omnihotels.com/hotels/homestead-virginia",
    skiresortinfoId: "omni-homestead",
  },

  // ============================================================
  // TENNESSEE (Southeast) - 1 resort
  // ============================================================
  {
    name: "Ober Gatlinburg",
    state: "TN",
    lat: 35.7061,
    lon: -83.5178,
    websiteUrl: "https://www.obergatlinburg.com",
    skiresortinfoId: "ober-gatlinburg",
  },

  // ============================================================
  // MARYLAND (Southeast) - 1 resort
  // ============================================================
  {
    name: "Wisp",
    state: "MD",
    lat: 39.5592,
    lon: -79.3647,
    websiteUrl: "https://www.wispresort.com",
    skiresortinfoId: "wisp",
  },

  // ============================================================
  // NEW MEXICO (Rockies) - 8 resorts
  // ============================================================
  {
    name: "Taos Ski Valley",
    state: "NM",
    lat: 36.5964,
    lon: -105.4544,
    websiteUrl: "https://www.skitaos.com",
    skiresortinfoId: "taos-ski-valley",
  },
  {
    name: "Angel Fire",
    state: "NM",
    lat: 36.3944,
    lon: -105.2833,
    websiteUrl: "https://www.angelfireresort.com",
    skiresortinfoId: "angel-fire",
  },
  {
    name: "Ski Santa Fe",
    state: "NM",
    lat: 35.7967,
    lon: -105.8033,
    websiteUrl: "https://www.skisantafe.com",
    skiresortinfoId: "ski-santa-fe",
  },
  {
    name: "Red River",
    state: "NM",
    lat: 36.7053,
    lon: -105.4097,
    websiteUrl: "https://www.redriverskiarea.com",
    skiresortinfoId: "red-river",
  },
  {
    name: "Ski Apache",
    state: "NM",
    lat: 33.3917,
    lon: -105.8,
    websiteUrl: "https://www.skiapache.com",
    skiresortinfoId: "ski-apache",
  },
  {
    name: "Sandia Peak",
    state: "NM",
    lat: 35.2103,
    lon: -106.4258,
    websiteUrl: "https://www.sandiapeak.com",
    skiresortinfoId: "sandia-peak",
  },
  {
    name: "Sipapu",
    state: "NM",
    lat: 36.0833,
    lon: -105.5167,
    websiteUrl: "https://www.sipapu.ski",
    skiresortinfoId: "sipapu",
  },
  {
    name: "Pajarito Mountain",
    state: "NM",
    lat: 35.8833,
    lon: -106.3833,
    websiteUrl: "https://www.pajaritomountain.com",
    skiresortinfoId: "pajarito-mountain",
  },

  // ============================================================
  // ARIZONA (Rockies) - 3 resorts
  // ============================================================
  {
    name: "Arizona Snowbowl",
    state: "AZ",
    lat: 35.3308,
    lon: -111.7117,
    websiteUrl: "https://www.snowbowl.ski",
    skiresortinfoId: "arizona-snowbowl",
  },
  {
    name: "Sunrise Park",
    state: "AZ",
    lat: 33.97,
    lon: -109.5828,
    websiteUrl: "https://www.sunrise.ski",
    skiresortinfoId: "sunrise-park",
  },
  {
    name: "Mt. Lemmon Ski Valley",
    state: "AZ",
    lat: 32.4417,
    lon: -110.7833,
    websiteUrl: "https://www.skithelemmon.com",
    skiresortinfoId: "mt-lemmon",
  },

  // ============================================================
  // ALASKA (West) - 10 resorts
  // ============================================================
  {
    name: "Alyeska",
    state: "AK",
    lat: 60.9656,
    lon: -149.1039,
    websiteUrl: "https://www.alyeskaresort.com",
    skiresortinfoId: "alyeska",
  },
  {
    name: "Eaglecrest",
    state: "AK",
    lat: 58.2917,
    lon: -134.5139,
    websiteUrl: "https://www.skijuneau.com",
    skiresortinfoId: "eaglecrest",
  },
  {
    name: "Arctic Valley",
    state: "AK",
    lat: 61.2456,
    lon: -149.5381,
    websiteUrl: "https://www.arcticvalley.org",
    skiresortinfoId: "arctic-valley",
  },
  {
    name: "Hilltop Ski Area",
    state: "AK",
    lat: 61.1394,
    lon: -149.7767,
    websiteUrl: "https://www.hilltopskiarea.org",
    skiresortinfoId: "hilltop-ski-area",
  },
  {
    name: "Moose Mountain",
    state: "AK",
    lat: 64.8639,
    lon: -147.6772,
    websiteUrl: "https://www.shredthemoose.com",
    skiresortinfoId: "moose-mountain-ak",
  },
  {
    name: "Mt. Aurora Skiland",
    state: "AK",
    lat: 64.9531,
    lon: -147.5164,
    websiteUrl: "https://www.skiland.org",
    skiresortinfoId: "mt-aurora-skiland",
  },
  {
    name: "Skeetawk",
    state: "AK",
    lat: 61.75,
    lon: -149.2667,
    websiteUrl: "https://www.skeetawk.com",
    skiresortinfoId: "skeetawk",
  },
  {
    name: "Mount Eyak",
    state: "AK",
    lat: 60.5417,
    lon: -145.7417,
    websiteUrl: "https://www.mteyak.org",
    skiresortinfoId: "mount-eyak",
  },
  {
    name: "Birch Hill",
    state: "AK",
    lat: 64.8833,
    lon: -147.7333,
    websiteUrl: "https://www.birchhillski.org",
    skiresortinfoId: "birch-hill",
  },
  {
    name: "Juneau Ski Club",
    state: "AK",
    lat: 58.3017,
    lon: -134.4194,
    websiteUrl: "https://www.skijuneau.com",
    skiresortinfoId: "juneau-ski-club",
  },

  // ============================================================
  // OHIO (Midwest) - 5 resorts
  // ============================================================
  {
    name: "Mad River Mountain",
    state: "OH",
    lat: 40.3167,
    lon: -83.6833,
    websiteUrl: "https://www.skimadriver.com",
    skiresortinfoId: "mad-river-mountain",
  },
  {
    name: "Boston Mills",
    state: "OH",
    lat: 41.25,
    lon: -81.5333,
    websiteUrl: "https://www.bmbw.com",
    skiresortinfoId: "boston-mills",
  },
  {
    name: "Brandywine",
    state: "OH",
    lat: 41.2333,
    lon: -81.5333,
    websiteUrl: "https://www.bmbw.com",
    skiresortinfoId: "brandywine",
  },
  {
    name: "Alpine Valley Ohio",
    state: "OH",
    lat: 41.5833,
    lon: -81.0,
    websiteUrl: "https://www.alpinevalleyohio.com",
    skiresortinfoId: "alpine-valley-ohio",
  },
  {
    name: "Snow Trails",
    state: "OH",
    lat: 40.6667,
    lon: -82.5333,
    websiteUrl: "https://www.snowtrails.com",
    skiresortinfoId: "snow-trails",
  },

  // ============================================================
  // IOWA (Midwest) - 4 resorts
  // ============================================================
  {
    name: "Sundown Mountain",
    state: "IA",
    lat: 42.5167,
    lon: -90.8333,
    websiteUrl: "https://www.sundownmtn.com",
    skiresortinfoId: "sundown-mountain",
  },
  {
    name: "Mt. Crescent",
    state: "IA",
    lat: 41.3833,
    lon: -95.85,
    websiteUrl: "https://www.skicrescent.com",
    skiresortinfoId: "mt-crescent",
  },
  {
    name: "Seven Oaks",
    state: "IA",
    lat: 42.0667,
    lon: -93.8833,
    websiteUrl: "https://www.sevenoaksrec.com",
    skiresortinfoId: "seven-oaks",
  },
  {
    name: "Sleepy Hollow",
    state: "IA",
    lat: 41.9667,
    lon: -91.6833,
    websiteUrl: "https://www.sleepyhollowiowa.com",
    skiresortinfoId: "sleepy-hollow",
  },

  // ============================================================
  // SOUTH DAKOTA (Midwest) - 2 resorts
  // ============================================================
  {
    name: "Terry Peak",
    state: "SD",
    lat: 44.3667,
    lon: -103.8667,
    websiteUrl: "https://www.terrypeak.com",
    skiresortinfoId: "terry-peak",
  },
  {
    name: "Great Bear",
    state: "SD",
    lat: 43.7833,
    lon: -96.7333,
    websiteUrl: "https://www.greatbearpark.com",
    skiresortinfoId: "great-bear",
  },

  // ============================================================
  // INDIANA (Midwest) - 2 resorts
  // ============================================================
  {
    name: "Paoli Peaks",
    state: "IN",
    lat: 38.5833,
    lon: -86.4333,
    websiteUrl: "https://www.paolipeaks.com",
    skiresortinfoId: "paoli-peaks",
  },
  {
    name: "Perfect North Slopes",
    state: "IN",
    lat: 39.15,
    lon: -84.8667,
    websiteUrl: "https://www.perfectnorth.com",
    skiresortinfoId: "perfect-north-slopes",
  },
];

async function seed() {
  console.log("Starting seed...");
  console.log(`Total resorts to seed: ${resortData.length}`);

  // Clear existing data
  console.log("Clearing existing resorts...");
  await db.delete(resorts);

  // Prepare resort records
  const resortRecords: NewResort[] = resortData.map((resort) => ({
    name: resort.name,
    slug: createSlug(resort.name),
    state: resort.state,
    region: stateRegions[resort.state] || null,
    latitude: resort.lat.toString(),
    longitude: resort.lon.toString(),
    timezone: stateTimezones[resort.state] || null,
    websiteUrl: resort.websiteUrl || null,
    skiresortinfoId: resort.skiresortinfoId || null,
  }));

  // Insert in batches of 50
  const batchSize = 50;
  let inserted = 0;

  for (let i = 0; i < resortRecords.length; i += batchSize) {
    const batch = resortRecords.slice(i, i + batchSize);
    await db.insert(resorts).values(batch);
    inserted += batch.length;
    console.log(`Inserted ${inserted}/${resortRecords.length} resorts...`);
  }

  // Log summary by region
  const regionCounts = resortRecords.reduce(
    (acc, r) => {
      const region = r.region || "Unknown";
      acc[region] = (acc[region] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );

  console.log("\nSeed complete!");
  console.log("\nResorts by region:");
  Object.entries(regionCounts)
    .sort((a, b) => b[1] - a[1])
    .forEach(([region, count]) => {
      console.log(`  ${region}: ${count}`);
    });
}

seed()
  .then(() => {
    console.log("\nSeed finished successfully.");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
